// Generated by the weekly content update.
export const weeklyContentRelease = Object.freeze({
  "schemaVersion": 1,
  "week": "2026-09-21",
  "timeZone": "Asia/Shanghai",
  "schedule": "Monday 09:00",
  "targetPerLanguage": 20,
  "english": {
    "articleIds": [
      "global-voices-es-org-2026-09-20-how-two-elections-reshaped-the-india-bangladesh-border",
      "standard-standardebooks-org-ebooks-pauline-e-hopkins-contending-forces",
      "global-voices-ome-a-form-of-resistance-in-conversation-with-catalan-artist-jaume-amigo",
      "global-voices-09-18-ecuador-detains-former-minister-jose-serrano-after-u-s-deportation",
      "global-voices-se-people-are-reinventing-political-protest-amid-civil-society-crackdown",
      "standard-debooks-org-ebooks-gustave-flaubert-sentimental-education-m-walter-dunne",
      "global-voices-reet-art-in-russia-is-dead-and-the-country-is-full-of-monumental-war-art",
      "global-voices-rg-2026-09-17-the-long-journey-from-indigenous-to-citizens-in-mozambique",
      "global-voices-09-16-singapores-permit-regime-undermines-the-citizens-right-to-protest",
      "nasa-mms-nasa-celebrates-restoration-of-guam-station-damaged-by-typhoon-mawar",
      "global-voices-15-what-indias-cockroach-protests-reveal-about-digital-authoritarianism",
      "global-voices-14-who-is-responsible-for-protecting-and-preserving-indigenous-cultures",
      "global-voices-peregrine-falcons-become-streaming-stars-of-the-34th-floor-in-australia",
      "global-voices-8-02-nepals-community-forests-offer-climate-solutions-one-leaf-at-a-time",
      "global-voices-beyond-citizenship-what-remains-when-the-state-refuses-to-recognise-you",
      "global-voices-assams-citizenship-amendment-act-caa-pathway-struggled-to-gain-traction",
      "global-voices-ily-like-insurrection-revisiting-trinidad-tobagos-first-emancipation-day",
      "global-voices-6-07-31-a-myanmar-artist-navigating-statelessness-and-activism-in-france",
      "global-voices-ces-org-2026-07-31-venezuela-is-burning-and-im-forced-to-watch-from-afar",
      "global-voices-0-the-journey-of-a-young-rohingya-man-from-genocide-to-survival-and-hope"
    ],
    "checkedAt": "2026-09-21T06:05:33.461Z",
    "count": 20,
    "shortfall": 0,
    "sourceErrorCount": 0
  },
  "cantonese": {
    "articleIds": [
      "hbl-00194-why",
      "hbl-my-pet",
      "hbl-the-stray-dog",
      "hbl-an-ice-lolly-for-free",
      "hbl-cat-rat-and-the-2d-shapes",
      "hbl-cat-rat-and-the-3d-shapes",
      "hbl-sitting-side-by-side",
      "hbl-the-game-of-shapes",
      "hbl-sharing-mangoes",
      "hbl-help-i-turned-upside-down",
      "yue-wikipedia-20324",
      "yue-wikipedia-59000",
      "yue-wikipedia-83903",
      "yue-wikipedia-111438",
      "yue-wikipedia-223031",
      "yue-wikipedia-261015",
      "yue-wikipedia-285542",
      "yue-wikipedia-127647",
      "yue-wikipedia-213690",
      "yue-wikipedia-267554"
    ],
    "checkedAt": "2026-09-21T06:05:33.461Z",
    "count": 20,
    "shortfall": 0,
    "sourceErrorCount": 0
  }
});
