// Generated by the weekly content update.
export const weeklyContentRelease = Object.freeze({
  "schemaVersion": 1,
  "week": "2026-09-14",
  "timeZone": "Asia/Shanghai",
  "schedule": "Monday 09:00",
  "targetPerLanguage": 20,
  "english": {
    "articleIds": [
      "global-voices-s-org-2026-09-13-as-casablancas-music-scene-grows-its-musicians-struggle",
      "global-voices-the-235th-anniversary-of-bois-caiman-means-for-haitis-memory-and-future",
      "standard-rdebooks-org-ebooks-edmund-burke-reflections-on-the-revolution-in-france",
      "nasa-elease-nasa-calls-for-proposals-to-accelerate-lunar-surface-technologies",
      "global-voices-herat-arrests-are-a-defining-moment-of-taliban-repression-in-afghanistan",
      "global-voices-and-more-complicit-an-interview-with-lebanese-british-artist-amale-khlat",
      "global-voices-of-cultural-revival-the-siraya-reclaim-their-indigenous-status-in-taiwan",
      "global-voices-t-is-like-to-run-a-business-as-a-woman-in-taliban-controlled-afghanistan",
      "global-voices-picture-of-how-indigenous-youth-are-treated-in-australias-justice-system",
      "global-voices-apan-ryukyuan-indigenous-claim-hindered-by-u-s-military-bases-in-okinawa",
      "global-voices-cameroon-are-adapting-to-eu-regulations-but-they-still-want-a-fair-price",
      "global-voices-ion-whose-development-the-maasai-struggle-over-land-in-northern-tanzania",
      "global-voices-what-does-home-mean-for-people-with-no-single-territory-connecting-them",
      "global-voices-6-08-06-when-chinese-parents-outsource-control-over-their-adult-children",
      "global-voices-gal-access-in-a-shrinking-space-building-ecosystems-to-end-statelessness",
      "global-voices-globalvoices-org-2026-08-05-indigenous-stories-are-global-stories",
      "global-voices-the-anatomy-of-erasure-indigenous-assyrian-women-and-forgotten-genocide",
      "global-voices-08-04-a-stateless-travelers-journey-through-ignorance-and-misinformation",
      "global-voices-s-org-2026-08-04-courts-and-unions-fail-to-protect-workers-in-kazakhstan",
      "global-voices-08-03-how-a-community-led-campaign-is-helping-save-nigerias-kam-language"
    ],
    "checkedAt": "2026-09-14T06:00:30.783Z",
    "count": 20,
    "shortfall": 0,
    "sourceErrorCount": 0
  },
  "cantonese": {
    "articleIds": [
      "hbl-seed-bank",
      "hbl-school-rules-and-regulations",
      "hbl-too-big-too-small",
      "hbl-what-is-the-password",
      "hbl-happy-heart",
      "hbl-grandmas-mango-tree",
      "hbl-why-dont-things-fall-up",
      "hbl-world-under-the-sea",
      "hbl-visit-to-the-beach-on-sunday",
      "hbl-butterfly",
      "hbl-dont-fear-the-dark-night",
      "hbl-a-day-with-my-son",
      "hbl-grandmas-walk-to-the-park",
      "hbl-coffee-millktea-and-yeunyeung",
      "hbl-orange",
      "hbl-the-great-artist",
      "hbl-lie",
      "hbl-when-will-mama-be-back",
      "hbl-seeds",
      "hbl-let-me-shine"
    ],
    "checkedAt": "2026-09-14T06:00:30.783Z",
    "count": 20,
    "shortfall": 0,
    "sourceErrorCount": 0
  }
});
