// Generated by the weekly content update.
export const weeklyContentRelease = Object.freeze({
  "schemaVersion": 1,
  "week": "2026-09-07",
  "timeZone": "Asia/Shanghai",
  "schedule": "Monday 09:00",
  "targetPerLanguage": 20,
  "english": {
    "articleIds": [
      "voa-s-com-a-studying-patterns-to-improve-your-writting-part-one-3427791-html",
      "voa-lish-voanews-com-a-the-blue-hotel-by-stephen-crane-part-one-4773641-html",
      "voa-sh-voanews-com-a-questions-answers-about-holiday-activities-6904240-html",
      "voa-s-com-a-celebrated-jumping-frog-calaveras-county-mark-twain-3160704-html",
      "voa-ish-voanews-com-a-grammar-for-making-new-year-s-resolutions-5226829-html",
      "voa-arningenglish-voanews-com-a-the-gift-of-the-magi-by-o-henry-4656574-html",
      "voa-earningenglish-voanews-com-a-everyday-grammar-and-christmas-4172368-html",
      "voa-arningenglish-voanews-com-a-american-stories-chicken-little-6947104-html",
      "voa-n-stories-how-the-animals-lost-their-tails-by-carl-sandburg-6956466-html",
      "voa-com-a-cask-of-amontillado-edgar-allan-poe-american-stories-3249195-html",
      "voa-ish-voanews-com-a-two-thanksgiving-day-gentlemen-by-o-henry-4656560-html",
      "voa-genglish-voanews-com-a-the-purloined-letter-edgar-allan-poe-3307412-html",
      "voa-ingenglish-voanews-com-a-the-tell-tale-heat-edgar-allan-poe-3538402-html",
      "global-voices-es-org-2026-08-19-the-invisible-crisis-that-strips-people-of-citizenship",
      "global-voices-razil-sees-a-rise-in-land-conflicts-and-the-murders-of-indigenous-people",
      "global-voices-globalvoices-org-2026-08-18-who-are-the-m23-rebels-in-eastern-drc",
      "global-voices-g-2026-08-17-who-was-here-first-the-two-meanings-of-indigenous-in-europe",
      "global-voices-earth-fragments-from-communities-overlooked-after-venezuelas-earthquakes",
      "global-voices-of-sexual-violence-raises-alarm-in-the-democratic-republic-of-the-congo",
      "global-voices-ransgender-person-raises-questions-about-faith-and-belonging-in-pakistan"
    ],
    "checkedAt": "2026-09-11T12:15:04.525Z",
    "count": 20,
    "shortfall": 0,
    "sourceErrorCount": 0
  },
  "cantonese": {
    "articleIds": [
      "hbl-whitey-the-cat",
      "hbl-we-are-grown-up-now",
      "hbl-saru-and-her-secret",
      "hbl-lost-found",
      "hbl-storyteller",
      "hbl-i-am-not-a-lustful-guy",
      "hbl-dinner-with-grandparents",
      "hbl-wendy-and-katy",
      "hbl-ten-princesses",
      "hbl-its-fun-with-friends",
      "hbl-brilliant-ying",
      "hbl-counting-little-legs",
      "hbl-the-money-saving-plan",
      "hbl-come-here-cat",
      "hbl-our-secret",
      "hbl-its-noisy",
      "hbl-bone-puzzle",
      "hbl-who-can-i-tell",
      "hbl-the-right-angle",
      "hbl-taller-shorter"
    ],
    "checkedAt": "2026-09-11T12:08:05.585Z",
    "count": 20,
    "shortfall": 0,
    "sourceErrorCount": 0
  }
});
